### ISSUE TITLE
Extension negotiation

### ISSUE THREAD

**Issue by chris-wood** [ietf-wg-privacypass/draft-ietf-privacypass-auth-scheme-extensions#2]
I wonder if it would be useful for origins to express what sort of extensions they want for a particular token. They could do this by including a list of extension types in the `WWW-Authenticate` challenge header. If clients don't want to provide the list of extensions they request, they could simply choose to not respond to the challenge. Without something like this, we would either have a default set of extensions sent by clients that are ultimately ignored by origins (which might be fine), or this the set of extensions would need to be configured between clients and origins.

**Comment by smhendrickson** [comment]
This is now addressed by #12
